import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import config from "../firebase";
import btn from "../public/btn_google_signin_dark_pressed_web.png";

const Home = () => {
  const googleLogin = () => {
    console.log("HELLO");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image
        src={btn}
        alt="login"
        className={styles.img}
        onClick={googleLogin}
      />
    </div>
  );
};

export default Home;
